server:
  port: 8888
encrypt:
  key: my-secret-encryption-key
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Parthi96/cloudconfig-blr-toll
          search-paths:
            - "station*"
  security:
    user:
      name: configuser
      password: configpass